### ISSUE TITLE
Featured image not displayed on pages.

### ISSUE THREAD

**Issue by akissz** [htmsk138/noto-simple#1]
The "Featured image(s)" display on "posts". The "Featured image(s)" do not display on "pages". So maybe the Featured image button needs to be removed from page edit or maybe the php needs to be fixed so the images do display when set on pages. In my opinion, please fix the php so images display on both pages and posts.

**Comment by htmsk138** [comment]
I fixed the issue and the update now should be available via WordPress admin panel. Thanks for reporting and getting in touch!
