### ISSUE TITLE
Date and time in posts

### ISSUE THREAD

**Issue by TomJensen16** [htmsk138/noto-simple#3]
Hi, this is not an issue, but a question.
Is it possible to get the time when the post is posted together with the date?

Thanks for a great theme.

**Comment by htmsk138** [comment]
@TomJensen16 
Hi, it's not possible now, but I could implement an option to switch display/hide time along with the date, if you could wait till November...I'm up to my neck in work this month :/

Glad you liked the theme, thank you!

**Comment by htmsk138** [comment]
@TomJensen16 
Updated the theme to implement this. You can enable the feature via Appearance -> Customize -> Display Settings. Sorry for the long wait!
