### ISSUE TITLE
Custom Footer Text Box

### ISSUE THREAD

**Issue by akissz** [htmsk138/noto-simple#5]
I want to request a feature. The ability to write a short code like [name], inside the Custom Footer Text Box. This would be a great addition! I mean currently the box only allows text. Without html and without short codes. Or maybe better. Make it possible to enter short codes and html in all the sections in Site Identity section. Have a wonderful day!

**Comment by htmsk138** [comment]
Hi, unfortunately shortcode is plugin's to implement. Footer text is already HTML-enabled and other entries in Site Identity section are WordPress defaults, so I'll leave it as is. Thank you.
